storage:
  redis:
    adapter: Lightna\Redis\App\Storage\Redis
    options:
      host: null
      port: null
      db: null
      persistent: true
      serializer: igbinary
  session_redis:
    adapter: Lightna\Redis\App\Storage\Redis
    options:
      host: null
      port: null
      db: null
      persistent: true
      timeout: 2
      data_type: string
      serializer: null
session_handler:
  redis: Lightna\Redis\App\Session\Handler
