indexer:
  changelog:
    tables:
      catalog_product_entity: [ entity_id ]
      catalog_product_entity_datetime: [ entity_id ]
      catalog_product_entity_decimal: [ entity_id ]
      catalog_product_entity_gallery: [ entity_id ]
      catalog_product_entity_int: [ entity_id ]
      catalog_product_entity_text: [ entity_id ]
      catalog_product_entity_tier_price: [ entity_id ]
      catalog_product_entity_varchar: [ entity_id ]
      catalog_product_index_price: [ ]
      catalog_product_index_price_replica: [ ]
      catalog_product_relation: [ ]
      catalog_product_super_attribute: [ product_id ]
      cms_page: [ page_id ]
      cms_page_store: [ page_id ]
      cataloginventory_stock_item: [ product_id ]
      catalog_product_website: [ product_id ]
      url_rewrite: [ entity_type, entity_id ]
      core_config_data: [ ]
      catalog_category_entity: [ entity_id ]
      catalog_category_entity_datetime: [ entity_id ]
      catalog_category_entity_decimal: [ entity_id ]
      catalog_category_entity_int: [ entity_id ]
      catalog_category_entity_text: [ entity_id ]
      catalog_category_entity_varchar: [ entity_id ]
      eav_attribute: [ ]
      eav_attribute_label: [ ]
      eav_attribute_option: [ ]
      eav_attribute_option_value: [ ]
      catalog_eav_attribute: [ ]
      cms_block: [ block_id ]
      cms_block_store: [ block_id ]
      inventory_source_item: [ sku ]
      inventory_reservation: [ sku ]
    batch:
      collectors:
        lightna_product: Lightna\Magento\App\Index\Changelog\Collector\Product
        lightna_cms_page: Lightna\Magento\App\Index\Changelog\Collector\CmsPage
        lightna_stock: Lightna\Magento\App\Index\Changelog\Collector\Stock
        lightna_inventory: Lightna\Magento\App\Index\Changelog\Collector\Inventory
        lightna_product_website: Lightna\Magento\App\Index\Changelog\Collector\ProductWebsite
        lightna_url_rewrite: Lightna\Magento\App\Index\Changelog\Collector\UrlRewrite
        lightna_config: Lightna\Magento\App\Index\Changelog\Collector\Config
        lightna_category: Lightna\Magento\App\Index\Changelog\Collector\Category
        lightna_attributes: Lightna\Magento\App\Index\Changelog\Collector\Attributes
        lightna_cms_block: Lightna\Magento\App\Index\Changelog\Collector\CmsBlock
  inventory:
    ignore_qty_change: true
  product:
    raw_value_attributes:
      - new
      - sale
